export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE";
export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const SEARCH_STUDENTS_REQUEST = "SEARCH_STUDENTS_REQUEST";
