export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";
export const DELETE_INSTRUCTOR_REQUEST = "DELETE_INSTRUCTOR_REQUEST";
export const UPDATE_INSTRUCTOR_REQUEST = "UPDATE_INSTRUCTOR_REQUEST";
export const ADD_INSTRUCTOR_REQUEST = "ADD_INSTRUCTOR_REQUEST";
export const SEARCH_INSTRUCTORS_REQUEST="SEARCH_INSTRUCTORS_REQUEST";

