export const FETCH_SUBJECTS_REQUEST = "FETCH_SUBJECTS_REQUEST";
export const FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS";
export const FETCH_SUBJECTS_FAILURE = "FETCH_SUBJECTS_FAILURE";
export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const UPDATE_SUBJECT_REQUEST = "UPDATE_SUBJECT_REQUEST";
export const ADD_SUBJECT_REQUEST = "ADD_SUBJECT_REQUEST";
export const SEARCH_SUBJECTS_REQUEST="SEARCH_SUBJECTS_REQUEST";