export const FETCH_FEEDBACKS_REQUEST = "FETCH_FEEDBACKS_REQUEST";
export const FETCH_FEEDBACKS_SUCCESS = "FETCH_FEEDBACKS_SUCCESS";
export const FETCH_FEEDBACKS_FAILURE = "FETCH_FEEDBACKS_FAILURE";
export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK_REQUEST = "UPDATE_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_REQUEST = "ADD_FEEDBACK_REQUEST";
export const SEARCH_FEEDBACKS_REQUEST="SEARCH_FEEDBACKS_REQUEST";